---
galaxy_info:
  author: "Joshua Lund"
  description: "Ansible role that installs the Shadowsocks secure SOCKS 5 proxy (http://shadowsocks.org)"
  license: MIT
  min_ansible_version: 1.3
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  categories:
    - networking
dependencies: []
